try to upgrade the es wild guess
Remove the max bucket query it's in the new version by default
took the redinnes code from versoin 8.5.1
And upgrade the image version

diff --git a/charts/tensorleap/templates/elasticsearch.yaml b/charts/tensorleap/templates/elasticsearch.yaml
--- a/charts/tensorleap/templates/elasticsearch.yaml
+++ b/charts/tensorleap/templates/elasticsearch.yaml
@@ -102,7 +102,7 @@ spec:
         runAsUser: 0
       containers:
         - name: elasticsearch
-          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
+          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
           imagePullPolicy: IfNotPresent
           readinessProbe:
             exec:
@@ -110,59 +110,62 @@ spec:
                 - sh
                 - -c
                 - |
-                  #!/usr/bin/env bash -e
-                  # If the node is starting up wait for the cluster to be ready (request params: "wait_for_status=green&timeout=1s" )
-                  # Once it has started only check that the node itself is responding
-                  START_FILE=/tmp/.es_start_file
-
-                  # Disable nss cache to avoid filling dentry cache when calling curl
-                  # This is required with Elasticsearch Docker using nss < 3.52
-                  export NSS_SDB_USE_CACHE=no
-
-                  http () {
-                    local path="${1}"
-                    local args="${2}"
-                    set -- -XGET -s
-
-                    if [ "$args" != "" ]; then
-                      set -- "$@" $args
-                    fi
-
-                    if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
-                      set -- "$@" -u "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
-                    fi
-
-                    curl --output /dev/null -k "$@" "http://127.0.0.1:9200${path}"
-                  }
-
-                  if [ -f "${START_FILE}" ]; then
-                    echo 'Elasticsearch is already running, lets check the node is healthy'
-                    HTTP_CODE=$(http "/" "-w %{http_code}")
-                    RC=$?
-                    if [[ ${RC} -ne 0 ]]; then
-                      echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} http://127.0.0.1:9200/ failed with RC ${RC}"
-                      exit ${RC}
-                    fi
-                    # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
-                    if [[ ${HTTP_CODE} == "200" ]]; then
-                      exit 0
-                    elif [[ ${HTTP_CODE} == "503" && "7" == "6" ]]; then
-                      exit 0
-                    else
-                      echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} http://127.0.0.1:9200/ failed with HTTP code ${HTTP_CODE}"
+                    # Exit if ELASTIC_PASSWORD in unset
+                    if [ -z "${ELASTIC_PASSWORD}" ]; then
+                      echo "ELASTIC_PASSWORD variable is missing, exiting"
                       exit 1
                     fi
 
-                  else
-                    echo 'Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )'
-                    if http "/_cluster/health?wait_for_status=green&timeout=1s" "--fail" ; then
-                      touch ${START_FILE}
-                      exit 0
+                    # If the node is starting up wait for the cluster to be ready (request params: "wait_for_status=green&timeout=1s" )
+                    # Once it has started only check that the node itself is responding
+                    START_FILE=/tmp/.es_start_file
+
+                    # Disable nss cache to avoid filling dentry cache when calling curl
+                    # This is required with Elasticsearch Docker using nss < 3.52
+                    export NSS_SDB_USE_CACHE=no
+
+                    http () {
+                      local path="${1}"
+                      local args="${2}"
+                      set -- -XGET -s
+
+                      if [ "$args" != "" ]; then
+                        set -- "$@" $args
+                      fi
+
+                      set -- "$@" -u "elastic:${ELASTIC_PASSWORD}"
+
+                      curl --output /dev/null -k "$@" "https://127.0.0.1:9200${path}"
+                    }
+
+                    if [ -f "${START_FILE}" ]; then
+                      echo 'Elasticsearch is already running, lets check the node is healthy'
+                      HTTP_CODE=$(http "/" "-w %{http_code}")
+                      RC=$?
+                      if [[ ${RC} -ne 0 ]]; then
+                        echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} https://127.0.0.1:9200/ failed with RC ${RC}"
+                        exit ${RC}
+                      fi
+                      # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
+                      if [[ ${HTTP_CODE} == "200" ]]; then
+                        exit 0
+                      elif [[ ${HTTP_CODE} == "503" && "8" == "6" ]]; then
+                        exit 0
+                      else
+                        echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} https://127.0.0.1:9200/ failed with HTTP code ${HTTP_CODE}"
+                        exit 1
+                      fi
+
                     else
-                      echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
-                      exit 1
+                      echo 'Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=1s" )'
+                      if http "/_cluster/health?wait_for_status=green&timeout=1s" "--fail" ; then
+                        touch ${START_FILE}
+                        exit 0
+                      else
+                        echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
+                        exit 1
+                      fi
                     fi
-                  fi
             failureThreshold: 3
             initialDelaySeconds: 10
             periodSeconds: 10
@@ -207,22 +210,4 @@ spec:
             - name: esconfig
               mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
               subPath: elasticsearch.yml
-          lifecycle:
-            postStart:
-              exec:
-                command:
-                  - bash
-                  - -c
-                  - |
-                    #!/bin/bash
-                    set -euo pipefail;
-
-                    chmod -R 777 /usr/share/elasticsearch/data
-
-                    while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L 127.0.0.1:9200/_cluster/health?wait_for_status=yellow&timeout=5s)" != "200" ]]; do sleep 3; done
-
-                    echo 'Setting zero-replicas index template';
-                    curl 127.0.0.1:9200/_template/zero-replicas -s --fail -XPUT -H 'Content-Type: application/json' -d '{"index_patterns":["*"],"settings":{"number_of_replicas":0}}'
-                    echo 'Updating elastic max bucket query limit'
-                    curl 127.0.0.1:9200/_cluster/settings -s --fail -XPUT -H 'Content-Type: application/json' -d '{"persistent":{"search.max_buckets":65000}}'
 {{ end }}
